### ISSUE TITLE
gherkin_lint breaks binding.pry

### ISSUE THREAD

**Issue by JESii** [funkwerk/gherkin_lint#3] opened 2016-07-28 16:42 UTC
We use pry and the binding.pry expression to debug our cucumber/step definitions.

When we added the gherkin_lint gem to our Gemfile (ruby 2.0,0, cucumber 1.3.17), binding.pry fails with:
    `wrong number of arguments (0 for 1..2) (ArgumentError).`
Removing the gem solved the problem.

**Comment by lindt** [comment] 2016-08-11 00:56
Thank you for your issue!

I needed a while, because I've been migrating from gherkin2 to gherkin4. It was a major refactoring. Nearly all files changed.
Could you try to reproduce it with such a newer version? Tag: 0.4.1.
Otherwise how could I reproduce your issue? I tried, but failed to stimulate the error you got.

**Comment by JESii** [comment] 2016-08-11 01:49
Thanks much for the follow-up.

I’ll work with the configuration we have at work and see if i can repeat it. There have already been some changes made to avoid the issue and the fellow who made the changes is out for the rest of the week.

Cheers…jon

Jon Seidel, CMC®
EDP Consulting, Inc. / www.edpci.com http://www.edpci.com/ / www.4mypasswords.com http://www.4mypasswords.com/
 http://www.4mypasswords.com/Effective Decisions... Priceless!
LinkedIn Profile http://www.linkedin.com/in/jonseidel
Technology that means Business - Since 1979
phone: 510-530-6314
fax: 510-531-1522

Results that Make the Difference! The Certified Management Consultant (CMC) mark is awarded to consultants who meet the strict standards defined by the Institute of Management Consultants USA (an ISO/IEC 17024:2003 Certifying Body), including examination by their peers, client evaluations, and a written examination evidencing their understanding of the IMC USA's Code of Ethics. The CMC is the only consulting certification that has been ISO-accredited and recognized by the insurance industry as reducing risk.
Check out IMC USA http://www.imcusa.org/?page=WHYHIREACMC for more information.

**Comment by JESii** [comment] 2016-08-11 01:50
Thanks much for the follow-up.

I’ll work with the configuration we have at work and see if i can repeat it. There have already been some changes made to avoid the issue and the fellow who made the changes is out for the rest of the week.

Cheers…jon

Jon Seidel, CMC®
EDP Consulting, Inc. / www.edpci.com http://www.edpci.com/ / www.4mypasswords.com http://www.4mypasswords.com/
 http://www.4mypasswords.com/Effective Decisions... Priceless!
LinkedIn Profile http://www.linkedin.com/in/jonseidel
Technology that means Business - Since 1979
phone: 510-530-6314
fax: 510-531-1522

Results that Make the Difference! The Certified Management Consultant (CMC) mark is awarded to consultants who meet the strict standards defined by the Institute of Management Consultants USA (an ISO/IEC 17024:2003 Certifying Body), including examination by their peers, client evaluations, and a written examination evidencing their understanding of the IMC USA's Code of Ethics. The CMC is the only consulting certification that has been ISO-accredited and recognized by the insurance industry as reducing risk.
Check out IMC USA http://www.imcusa.org/?page=WHYHIREACMC for more information.

**Comment by lindt** [comment] 2016-12-01 10:27
did it work? could this issue be closed?

**Comment by lindt** [comment] 2016-12-08 12:24
I guess it's closed. Will close the issue now. If it occurs again, please reopen the issue.
Thank You.

**Closed as completed by lindt** 2016-12-08 12:24 UTC
